# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=example --execute "SHOW DATABASES;"'
      timeout: 20s
      retries: 10
  server:
    image: tiyuli-expense-api
    ports:
      - "50051:50051"
    depends_on:
      db:
        condition: service_healthy
