# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=example --execute "SHOW DATABASES;"'
      timeout: 5s
      retries: 10
    volumes:
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
  expense-api:
    image: tiyuli-expense-api
    ports:
      - "50051:50051"
    environment:
      TIYULI_EXPENSE_API_PORT: 50051
      TIYULI_EXPENSE_DB_USER: root
      TIYULI_EXPENSE_DB_PASS: example
      TIYULI_EXPENSE_DB_ADDRESS: db
      TIYULI_EXPENSE_DB_PORT: 3306
      TIYULI_EXPENSE_DB_NAME: tiyuli
    depends_on:
      db:
        condition: service_healthy
