// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: expense/get_expense.proto

package expense

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetExpenseByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetExpenseByIdRequest) Reset() {
	*x = GetExpenseByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expense_get_expense_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExpenseByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpenseByIdRequest) ProtoMessage() {}

func (x *GetExpenseByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_get_expense_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpenseByIdRequest.ProtoReflect.Descriptor instead.
func (*GetExpenseByIdRequest) Descriptor() ([]byte, []int) {
	return file_expense_get_expense_proto_rawDescGZIP(), []int{0}
}

func (x *GetExpenseByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetExpenseByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expense *Expense `protobuf:"bytes,1,opt,name=expense,proto3" json:"expense,omitempty"`
}

func (x *GetExpenseByIdResponse) Reset() {
	*x = GetExpenseByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expense_get_expense_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExpenseByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpenseByIdResponse) ProtoMessage() {}

func (x *GetExpenseByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_get_expense_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpenseByIdResponse.ProtoReflect.Descriptor instead.
func (*GetExpenseByIdResponse) Descriptor() ([]byte, []int) {
	return file_expense_get_expense_proto_rawDescGZIP(), []int{1}
}

func (x *GetExpenseByIdResponse) GetExpense() *Expense {
	if x != nil {
		return x.Expense
	}
	return nil
}

var File_expense_get_expense_proto protoreflect.FileDescriptor

var file_expense_get_expense_proto_rawDesc = []byte{
	0x0a, 0x19, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x65, 0x78,
	0x70, 0x65, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x74, 0x69, 0x79,
	0x75, 0x6c, 0x69, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x1a, 0x15, 0x65, 0x78, 0x70,
	0x65, 0x6e, 0x73, 0x65, 0x2f, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4b, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x69, 0x79, 0x75, 0x6c, 0x69, 0x2e,
	0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x52,
	0x07, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x64, 0x65, 0x64, 0x72, 0x6f, 0x39, 0x38, 0x37,
	0x2f, 0x74, 0x69, 0x79, 0x75, 0x6c, 0x69, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x65,
	0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_expense_get_expense_proto_rawDescOnce sync.Once
	file_expense_get_expense_proto_rawDescData = file_expense_get_expense_proto_rawDesc
)

func file_expense_get_expense_proto_rawDescGZIP() []byte {
	file_expense_get_expense_proto_rawDescOnce.Do(func() {
		file_expense_get_expense_proto_rawDescData = protoimpl.X.CompressGZIP(file_expense_get_expense_proto_rawDescData)
	})
	return file_expense_get_expense_proto_rawDescData
}

var file_expense_get_expense_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_expense_get_expense_proto_goTypes = []any{
	(*GetExpenseByIdRequest)(nil),  // 0: tiyuli.expense.GetExpenseByIdRequest
	(*GetExpenseByIdResponse)(nil), // 1: tiyuli.expense.GetExpenseByIdResponse
	(*Expense)(nil),                // 2: tiyuli.expense.Expense
}
var file_expense_get_expense_proto_depIdxs = []int32{
	2, // 0: tiyuli.expense.GetExpenseByIdResponse.expense:type_name -> tiyuli.expense.Expense
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_expense_get_expense_proto_init() }
func file_expense_get_expense_proto_init() {
	if File_expense_get_expense_proto != nil {
		return
	}
	file_expense_expense_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_expense_get_expense_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetExpenseByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expense_get_expense_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetExpenseByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_expense_get_expense_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_expense_get_expense_proto_goTypes,
		DependencyIndexes: file_expense_get_expense_proto_depIdxs,
		MessageInfos:      file_expense_get_expense_proto_msgTypes,
	}.Build()
	File_expense_get_expense_proto = out.File
	file_expense_get_expense_proto_rawDesc = nil
	file_expense_get_expense_proto_goTypes = nil
	file_expense_get_expense_proto_depIdxs = nil
}
